### ISSUE TITLE
Error!help me

### ISSUE THREAD

**Issue by guohuihot** [nfroidure/gulp-iconfont#103]
![qq](https://cloud.githubusercontent.com/assets/3119995/12082346/33b1ed94-b2cc-11e5-913a-17361fe19a73.png)

**Comment by nfroidure** [comment]
Please provide me the inputted TTF font.

**Comment by nfroidure** [comment]
Closing this issue since it is a duplicate of https://github.com/nfroidure/ttf2woff2/issues/23
