### ISSUE TITLE
the generated file is incorrect.

### ISSUE THREAD

**Issue by wuanrin** [nfroidure/gulp-iconfont#107]
my svg is 
![-3](https://cloud.githubusercontent.com/assets/8286811/12324818/6de5fe24-bb00-11e5-9d2e-013ced66823d.jpg)
generated file is 
![-2](https://cloud.githubusercontent.com/assets/8286811/12324854/c6c42bce-bb00-11e5-957b-832e7f91afe8.jpg)

**Comment by nfroidure** [comment]
Please provide the SVG file and also follow the guide for preparing your SVG icons available in the README.

**Comment by wuanrin** [comment]
the problem was solved. the problem is in the SVG file. Thank you!
