### ISSUE TITLE
generate fonts (ttf,woff,eot,woff2) from .svg font file, not icons

### ISSUE THREAD

**Issue by evilebottnawi** [nfroidure/gulp-iconfont#109]
It is possible? If i pipe svg file font, plugin throw error:
```bash
Error: Invalid character in entity name
Line: 11
Column: 76
Char: =
```
But it is not icon, it is svg font file.

**Comment by nfroidure** [comment]
This is not the point of gulp-iconfont. You can use gulp-(svg2ttf|ttf2eotttf2woffttf2woff2) separately to achieve that.

**Comment by evilebottnawi** [comment]
@nfroidure If i write ttf file in stream, i generate other extension (eot, woff, woff2) work fine. I think need option for generate ttf font file if i write in stream svg font file. In another case, the generation will have to gulp-(svg2ttf|ttf2eot|ttf2woff|ttf2woff2) in package.json and write similar code as in this plugin. It is not comfortable.

**Comment by nfroidure** [comment]
Being able to write a TTF file is clearly a side effect, i subscribe to the "Do one thing and do it well" and the gulp-iconfont purporse is only to build font from SVG icons.

It doesn't cost much efforts to use its submodules separately. If you prefer, you can also create a module for that, say gulp-font ;).

**Comment by evilebottnawi** [comment]
@nfroidure maybe simple add option for this feature and we get `gulp-font` without breaking backward compatibility

**Comment by evilebottnawi** [comment]
@nfroidure and it is one thing (generate fonts)

**Comment by nfroidure** [comment]
It is not that simple since svg icons and svg font have the same extension name. Would be hard to implement and slowdown the overall module for an edge case that can be covered by simply using this module dependencies.
