### ISSUE TITLE
Task does not end with Gulp 4

### ISSUE THREAD

**Issue by thasmo** [nfroidure/gulp-iconfont#113]
This is my (simplified) task:
```js
return gulp.src('src/**/*.svg')
	.pipe(plumber())
	.pipe(iconfont(options))
	.pipe(gulp.dest('dist/'));
```
Using `gulp <task>` with Gulp 4 executes the task, creates the font, but doesn't end the task. I have to press `ctrl+c` to forcefully stop it. I have various other gulp plugins in use which don't have this problem.

**Comment by nfroidure** [comment]
Please, configure a small repo with a full end to end use case since i cannot reproduce bugs without it.

Did you tried to remove plumber() ?

**Comment by thasmo** [comment]
Absolutely invalid. :) Everything works file, the problem was on my side. Thanks for the awesome plugin!

**Comment by nfroidure** [comment]
You're welcome ;).
