### ISSUE TITLE
Virus detected after npm install

### ISSUE THREAD

**Issue by tmhrtwg** [nfroidure/gulp-iconfont#120]
I've never seen this one before. Could be a false positive, or do you guys have this as well?

![npm-install-virus](https://cloud.githubusercontent.com/assets/3918317/13722173/18e4bfaa-e83c-11e5-9747-502cd94fbf3d.png)
_It says it has detected a virus inside a submobule used by gulp-iconfont._

I use Windows 7 with the paid AVG version.

**Comment by TylerYang** [comment]
Actually there are two issues about this. 
https://github.com/nfroidure/ttf2woff2/issues/17 https://github.com/nfroidure/ttf2woff2/issues/7#issuecomment-125086036

**Comment by tmhrtwg** [comment]
Thanks! Didn't find that one. Time for a new virus scanner I think :)

**Comment by TylerYang** [comment]
; )
