### ISSUE TITLE
IE shows icons with vertical offset

### ISSUE THREAD

**Issue by RobeeeJay** [nfroidure/gulp-iconfont#121]
Note that for this to work it relies on a version bump in gulp-svg2ttf, which is also sitting in a PR there. So I'd merge that one in, then the CI build will pass for this.

Fix with version bump here:
https://github.com/nfroidure/gulp-iconfont/pull/119

**Comment by RobeeeJay** [comment]
@nfroidure any chance of this PR being merged? :(

**Comment by nfroidure** [comment]
Hi, sorry about that. Had no time to work on it. Since the build fails, it needs a bit of work to get it work https://travis-ci.org/nfroidure/gulp-svg2ttf/jobs/114551504

**Comment by RobeeeJay** [comment]
Thanks for the response! I suspect build is broken because of the matching PR in svg2tff that also needs merging:
https://github.com/nfroidure/gulp-svg2ttf/pull/7

But that appears broken too according to travis, quite why I'm not sure. I don't really understand what the tests are checking. :(

**Comment by nfroidure** [comment]
They are are just checking the ttf font remain the same so i know when something changed. Not perfect but it's better than nothing.

**Comment by RobeeeJay** [comment]
Are you discontinuing gulp-iconfont and gulp-svg2ttf? :(

**Comment by nfroidure** [comment]
I have less time to give for gulp-iconfont and that's why i can't merge PRs that do not keep the tests working. Fixing tests in gulp-svg2ttf will get the PR merged and the module published.

**Comment by RobeeeJay** [comment]
Tests in gulp-svg2ttf fixed!

**Comment by nfroidure** [comment]
Thanks, published as gulp-iconfont 8.0.0

**Comment by RobeeeJay** [comment]
Thanks!
