### ISSUE TITLE
Codepoint from file name

### ISSUE THREAD

**Issue by loominade** [nfroidure/gulp-iconfont#124]
I'd like to explicitly map the file `U+2190.svg` to the codepoint `U+2190` and `U+1F4A9.svg` to the codepoin `U+1F4A9`. Is there a way to do just that?

**Comment by nfroidure** [comment]
Are you aware of https://github.com/nfroidure/gulp-svgicons2svgfont#optionsprependunicode ?

Anyway you can do whatever you'd want to with https://github.com/nfroidure/gulp-svgicons2svgfont#optionsmetadataprovider
