### ISSUE TITLE
Vertical alignment varies between browsers.

### ISSUE THREAD

**Issue by roelvanhintum** [nfroidure/gulp-iconfont#13]
.eot fonts have different alignments than the .ttf .woff and .svg fonts.
As always this means that my layout on Internet Explorer (including IE11) is incorrect.

To be clear, all icons render normally centered on other browsers. I only configured the fontName and appendCodepoints, the rest is default.

Is there a workaround for this?

**Comment by thamagnetix** [comment]
I'm having this exact probem. but cant find the releases (1.2.0 & 2.1.0) that should solve this - anything im missing?

**Comment by nfroidure** [comment]
It was gulp-iconfont 0.2.1 ;). Just updated deps and published the 1.0.1, hope it helps. Let me know if the issue persists.

**Comment by thamagnetix** [comment]
Thanks for such a quick response. Still having the same issue though. But if i use iconmoon to convert the svg-font its perfect, so its probably still the dependencies thats not up to date it their repos ? - http://imgur.com/CJy62GY - anyways thanks, ill try to work around it.

**Comment by nfroidure** [comment]
You should report this issue to svg2tff or ttf2woff projects imo it would help them to improve it.

**Comment by thamagnetix** [comment]
Your are absolutely right - I'll do that :)
