### ISSUE TITLE
Fontfiles binary diffs without changins sources

### ISSUE THREAD

**Issue by thybzi** [nfroidure/gulp-iconfont#130]
We're using `gulp-iconfont` on several projects, generating `ttf` and `woff` font formats.

The same thing happens at all of them: after regenerating fonts without any source SVG changes produces binary diff on both `woff` and `ttf`.

Is that meta info, timestamp, or whatever?

That can be safely ignored on projects with generated files gitignored, _but not on github jekyll projects that cannot run gulp on deploy_, and thus need those binary to be committed.

How can I disable this diff? Thanks in advance.

Here is a sample binary diff of `woff` file.

![woff_binary_diff](https://cloud.githubusercontent.com/assets/1572675/18035278/d76e8164-6d5b-11e6-976e-6607192b2d3f.png)

**Comment by nfroidure** [comment]
See the timestamp option https://github.com/nfroidure/gulp-iconfont#options

**Comment by thybzi** [comment]
Thanks for an answer.
First, `timestamp` seems to be `svg2ttf` options, then how does it affect `woff` file?
Second, I already tried to set this option to `null`, both font files keep changing every time (file checksum also differs).

**Comment by nfroidure** [comment]
Just set it to a timestamp. That's all you have to know to solve your issue. If you want more informations, you can read the code but i already spent enough time on real issue. You can also ask StackOverflow.

**Comment by thybzi** [comment]
Setting `timestamp` option to `0` (which is valid Unix timestamp) solves the problem. 
Thanks!
