### ISSUE TITLE
Embed data:uri

### ISSUE THREAD

**Issue by gabrieledarrigo** [nfroidure/gulp-iconfont#133]
Hello!
Thank you all for the huge work on the library!
Just a question, there's a way to embed the generated font in data:uri format, like this one:

https://github.com/sapegin/grunt-webfont#embed

Thank you for any answer!

Gabriele

**Comment by nfroidure** [comment]
Would merge a tested PR adding this feature.

**Comment by nfroidure** [comment]
Could be down downstream in another plugin so closing.
