### ISSUE TITLE
appendCodepoints does nothing ?

### ISSUE THREAD

**Issue by ashjs** [nfroidure/gulp-iconfont#137]
Hi,

I believed this option will prefix my icons svg files but, with or without, nothing changes.

Is there something that I missed or didn't understand for this option ?

Here my code:

`const gulp        = require('gulp');
const iconfont    = require('gulp-iconfont');
const consolidate = require('gulp-consolidate');
const rename      = require('gulp-rename');

module.exports = function(config) {
  return function() {
    return gulp.src(config.inputPath)
      .pipe(iconfont({
        fontName: config.fontName,
        formats: config.fontFormats,
        normalize: true,
        appendCodepoints: true,
        startUnicode: 0xf101,
      }))

      .on('glyphs', function(glyphs) {
        var options = {
          glyphs: glyphs.map(function(glyph) {
            return { name: glyph.name, codepoint: glyph.unicode[0].charCodeAt(0)};
          }),
          fontName: config.fontName,
          fontPath: config.outputPath,
          fontFormats: config.fontFormats,
          cssPath: config.cssPath,
          exempleCssPath: config.exempleCssPath,
        };

        gulp.src(config.templatePath)
          .pipe(consolidate('lodash', options))
          .pipe(rename({ basename:'_npc-icons' }))
          .pipe(gulp.dest(config.templateOutputPath));

        return gulp.src(config.exemplePath)
          .pipe(consolidate('lodash', options))
          .pipe(gulp.dest(config.exempleOutputPath));
      })
      .pipe(gulp.dest(config.outputPath));
  }
}`

The config if needed: 

`const config = {
	inputPath: './source/vectors/*.svg',
	outputPath: path.join(__dirname, '../build/fonts'),
	fontName: 'npcicons',
	fontFormats: ['ttf', 'eot', 'woff', 'svg', 'woff2'],
	templatePath: path.join(__dirname, '../fonts/npcicons/template.scss'),
	templateOutputPath: path.join(__dirname, '../source/sass/commun'),
	exemplePath: path.join(__dirname, './icons-font.html'),
	exempleOutputPath: path.join(__dirname, '../fonts/npcicons'),
};`

Thanks for your help.

**Comment by nfroidure** [comment]
The option name actually changed due to a bad naming at the very beginning of the project https://github.com/nfroidure/gulp-iconfont#options

options.prependUnicode
