### ISSUE TITLE
startUnicode option

### ISSUE THREAD

**Issue by alonrazor** [nfroidure/gulp-iconfont#142]
I'm trying to implement **option.startUnicode**, and always receiving the same starting count of: "\E001"

in the options i'm passing:
**startUnicode: 0xEA01**
and playing with the values but the generated font and SCSS always comes back "\E001" and counting... 
Am I missing something? 
How would be able to get a different starting count than the default?

Regards,

**Comment by nfroidure** [comment]
Which version do you use ? This feature has been renamed if I remember well only a few versions ago.

Note that at least you can provide you own logic for codepoints incrementation: https://github.com/nfroidure/gulp-svgicons2svgfont#optionsmetadataprovider

**Comment by alonrazor** [comment]
Thanks for the reply, I'm using the latest version 8.0.1

Managed to solve it by adding **firstGlyph** like this:

.pipe(**iconfontCss**({
                firstGlyph: 0xEA01,
 }))
            .pipe(**iconfont**({
              startUnicode: 0xEA01,
 }))
