### ISSUE TITLE
Font glyphs aren't converted properly and are pretty worse comparing with their SVG icons.

### ISSUE THREAD

**Issue by gladisihor** [nfroidure/gulp-iconfont#143]
Font glyphs aren't converted properly and are pretty worse comparing with their SVG icons.
I wrote normalize:true and fontHeight: 1001 in the gulp options, but it didn't resolve my problem at all...

![fonts issue](https://user-images.githubusercontent.com/15730570/27277130-e99bece2-54e5-11e7-816b-22bdb791c85d.jpeg)
![gulp options](https://user-images.githubusercontent.com/15730570/27277455-f8571bde-54e6-11e7-8110-c8010baf928b.png)

**Comment by nfroidure** [comment]
You should try the last 6.0.0 version which contains a fix that could be related to your issue: https://github.com/nfroidure/gulp-iconfont/issues/146

**Comment by gladisihor** [comment]
It still reproduced in version **8.0.1** ( `"gulp-iconfont": "^8.0.1"` )

**Comment by gladisihor** [comment]
It still reproduced in version 8.0.1 ( "gulp-iconfont": "^8.0.1" )

2017-07-15 19:10 GMT+03:00 Nicolas Froidure <notifications@github.com>:

**Comment by aseem2625** [comment]
@nfroidure ye, prob still remains..using v9.0.0

**Comment by NaridaL** [comment]
If you're still having this issue, I just pushed a version which updates the gulp-svgicons2svgfont dependency.

**Comment by nfroidure** [comment]
Closing since no news. Please reopen if the problem persists.
