### ISSUE TITLE
Font Icon Glyph codes not showing in terminal 

### ISSUE THREAD

**Issue by JordyVialoux** [nfroidure/gulp-iconfont#144]
Hi there, 

Using gulp-iconfont for the first time. 

When running `gulp iconfont` the glyph codes are not being populated within my terminal and instead displaying question marks where the code should be - see screenshot. 

![image](https://user-images.githubusercontent.com/6464307/27425102-3140655a-572f-11e7-8519-783071152f68.png)

The fonts do generate the font icon file and I can see the fonts within the font file which is great however, no codes to reference them within Css.

Here is my gulp task: 

```
const glyphFontName = 'icon'

//Font Icons
gulp.task('iconfont', () => {
    gulp.src(['src/app/assets/icons/*.svg'])
        .pipe(iconfontCss({
          fontName: 'icon-font',
          path: 'src/app/assets/less/common/icons.less',
          targetPath: 'build/generated' + glyphFontName + '.less',
          cssClass: 'i',
          centerHorizontally: true,
          appendUnicode: true,
          normalize:true,
          fontHeight: 1001,
          prependUnicode: true
        }))
        .pipe(iconfont({
            fontName: glyphFontName,
            formats: [
                'ttf',
                'eot',
                'woff',
                'woff2'
            ],
        }))
        .on('glyphs', (codepoints, options) => {
          console.log("CODEPOINTS", codepoints, options);
        })
        .pipe(gulp.dest('build/icons'))
})
```

I have wondered if there was an issue with my icons however, they render just fine here: [](https://jsfiddle.net/rhgp12zb/) 

Please advise on this as I cannot find solutions online regarding this. Css being used is .less if that helps the situation.

**Comment by nfroidure** [comment]
No issue, I think your terminal just do not render unicode private codepoints which is not surprising.
