### ISSUE TITLE
woff2 getting added in css when not added in formats

### ISSUE THREAD

**Issue by aseem2625** [nfroidure/gulp-iconfont#145]
As said in title, I'm not adding woff2 option inside
```
.pipe(
  iconfont({
    fontName: fontName,
    formats: ['svg', 'ttf', 'eot', 'woff'],
    normalize: true,
    prependUnicode: true, // recommended option
    fontHeight: 1001,
  })
)
```
But it's still adding this line inside css generated even when the `.woff2` file isn't generated.
`url('./icons.woff2') format('woff2'),`

How to deal with this, I don't need woff2.

**Comment by nfroidure** [comment]
`gulp-iconfont` do not generate CSS, you probably have to change another plugin configuration.

**Comment by aseem2625** [comment]
oh my bad. Didn't realize this.
