### ISSUE TITLE
How to add ligatures?

### ISSUE THREAD

**Issue by loominade** [nfroidure/gulp-iconfont#148]
According to #19 ligatures are supported. 

But how does it work? with `prependUnicode: true` I'd assume I have to name my files like `u1F4C4u1F47E-space_invader-on-page.svg` in order to create the 📄👾-Ligature (Page facing up/space invader).

However that results in a character that is a duplicate of the already existing 📄-Character. Am I doing something wrong? Is this a bug?

**Comment by nfroidure** [comment]
Please drop in the full configuration you used. I never used that feature myself but you can also share a full working repo to allow us to check the problem.

**Comment by loominade** [comment]
I created a minimum setup to reproduce this but and it turns out to be a bug in google chrome which  refuses to display certain ligatures. gulp-iconfont seems to work exactly as I expected. Please close this issue.

Sorry

**Comment by nfroidure** [comment]
No problem. Have a nice day.
