### ISSUE TITLE
Error when launching iconfont task - Unexpected token ...

### ISSUE THREAD

**Issue by geosenna** [nfroidure/gulp-iconfont#151]
Hi,

When launching the task I get this error:
 
`C:\xxx\node_modules\gulp-iconfont\node_modules\gulp-svgicons2svgfont\src\index.js:38
    gutil.log(...['gulp-svgicons2svgfont:'].concat(
              ^^^
SyntaxError: Unexpected token ...`

Any idea about this?

**Comment by NaridaL** [comment]
You must be using an old version of node which doesn't support spread operators.

**Comment by nfroidure** [comment]
Closing since it is an unsupported version of Node.
