### ISSUE TITLE
Breaking changes not reflected in semver?

### ISSUE THREAD

**Issue by htulipe** [nfroidure/gulp-iconfont#153]
Hi, more a question/suggestion than a bug report but, between 9.0.0 and 9.0.1, a [commit](https://github.com/nfroidure/gulp-iconfont/commit/f2a141c46bf0fdff523c0ece9a550ed2c152d971) updated minimum Node version. While it totally make sense to do so, IMHO, the npm version should have been updated at least to 9.1.0 since it's a breaking change.  Typically running `yarn upgrade`on my project updated gulp-iconfont automatically (because only patch number had changed) resulting in breaking my build (because I had node 6.10.5).

Anyway, those are just my two cents, I don't know if you're following semver. :)

Thanks for your work

**Comment by nfroidure** [comment]
We do, but shit happens. Thanks for reporting.
