### ISSUE TITLE
Custom characters

### ISSUE THREAD

**Issue by Dobby89** [nfroidure/gulp-iconfont#16]
Would it be possible to define the characters which each svg gets assigned to? At the minute they just seem to go up from '\E001' '\E002' '\E003' etc. So if I add a new svg to the folder of icons after running the task the first time, the characters get replaced and no longer match up with the symbols from the last time the font files were generated.

I'm thinking something along the lines of the following maybe (forgive me - I'm not a javascript man, but hopefully this makes sense).

``` javascript
characterArray = new Array();
characterArray['chevron-up.svg'] = '^';
characterArray['chevron-right.svg'] = '>';

gulp.task('Iconfont', function(){
  gulp.src(['assets/icons/*.svg'])
    .pipe(iconfont({
      fontName: 'myfont',
      overrideCharacter: characterArray
    }))
    .pipe(gulp.dest('www/fonts/'));
});
```

**Comment by Misiu** [comment]
@Dobby89 thanks for writing this excellent tutorial.
I'm planning to use gulp inside visual studio and right now I'm setting everything up. I was wondering if it will be possible to generate custom font for all my icons, but right now I should have everything withing in minutes! Thanks again.

**Comment by Dobby89** [comment]
@Misiu You're welcome. I hope you get everything sorted. Come back again if you're stuck because I've got a few more tips which could be helpful after using this several times now.

**Comment by daviestar** [comment]
@Dobby89 just starting to implement this functionality too and your tutorial looks good (thanks!). what are your extra tips?

**Comment by Dobby89** [comment]
@daviestar

1. Save all the SVG files on a square canvas with a 1px gap around the edges. I personally use a canvas/artboard of 128 x 128px with the icon placed centrally [http://screencast.com/t/Xf0lsNo4j](http://screencast.com/t/Xf0lsNo4j). If the icon isn't square, or 1:1 width:height ratio, then just make sure it's longest edge is 126px.
2. When saving the SVGs out, use the following settings [http://screencast.com/t/cmRFuCTyhS](http://screencast.com/t/cmRFuCTyhS).
3. In the gulp task, set `fontHeight: 1001`. I found this fixes badly rendered icons.

I think that's the main ones I can remember. I hope it makes sense, but feel free to ask more if necessary and refer to my [Gulp Boilerplate](https://github.com/Dobby89/gulp-boilerplate) project which uses it.

**Comment by Dobby89** [comment]
@daviestar I just remembered another tip...

Don't run the iconfont task directly on your SVGs. Instead, copy them to a temporary directory first and then run it. This stops the plugin renaming your files from `arrow.svg` to `uE001-arrow.svg`, which I find is quite annoying.

**Comment by daviestar** [comment]
@Dobby89 thanks for all the tips!

I've spent quite a while working on a 'batteries included' gulpfile.  There is breaking change in `gulp-iconfont` after @Dobby89 's tutorial (the `codepoints` event has been renamed to `glyphs`). 

Below is a quick copy/paste of both my `icon-font` task as well as my `fonts` task (they talk to one another).  Let me know if you have any questions.

##### dependencies
```javascript
var path        = require('path');
var del         = require('del');
var iconFont    = require('gulp-iconfont');
var consolidate = require('gulp-consolidate');
var rename      = require('gulp-rename');
var tap         = require('gulp-tap');

(also install underscore/lodash as dep or dev-dep)
```
##### my config object and helper function
```javascript
var config = {
    proxy:  'skeleton.dev',
    src:    'src',
    dest:   'public',
    assets: 'public/assets',
    fonts:  'src/fonts',
    temp:   'node_modules/_temp',
    ext: {
        js:     ['js', 'hbs'],
        css:    ['sass', 'scss', 'css'],
        images: ['svg', 'png', 'jpg', 'gif'],
        fonts:  ['ttf', 'eot', 'woff', 'woff2'],
        html:   ['html', 'php']
    }
};

function globExt(array) {
    return '.{'+array.join(',')+'}';
}
```

##### gulp tasks
```javascript
gulp.task('fonts', function(cb) {
    var fontPath = config.assets+'/fonts';
    var fontObj = {
        path: 'fonts/',
        exts: config.ext.fonts,
        fonts: {}
    };

    gulp.src(config.fonts+'/**/*'+globExt(config.ext.fonts))
        .pipe(tap(function(file) {
            var f = path.parse(file.path);
            if(!fontObj.fonts[f.name]) fontObj.fonts[f.name] = [];
            fontObj.fonts[f.name].push(f.ext);
        }))
        .pipe(gulp.dest(function(file) {
            file.path = file.base + path.basename(file.path);
            return fontPath;
        }))
        .on('end', function() {
            gulp.src(config.fonts+'/_fonts.tmpl')
                .pipe(consolidate('underscore', fontObj))
                .pipe(rename('fonts.sass'))
                .pipe(gulp.dest(config.fonts))
                .on('end', function() { cb() });
        });
});

gulp.task('icon-font', function(cb) {
    del(config.temp).then(function() {
        var tempFontsPath = config.temp+'/fonts';
        var timestamp = Math.round(Date.now() / 1000);
        var counter = 0;
        var fontObj = { className: 'icon' };

        gulp.src(config.src+'/**/*-icon.svg')
            .pipe(tap(function() { counter++ }))
            .pipe(gulp.dest(function(file) {
                file.path = file.base + path.basename(file.path);
                return tempFontsPath;
            }))
            .on('end', function() {
                if(!counter) { cb() }  // needed to properly end the task if there are no icons
                gulp.src(tempFontsPath+'/*.svg')
                    .pipe(iconFont({
                        fontName: 'icons',
                        appendUnicode: true,
                        normalize: true,
                        appendCodepoints: true,
                        formats: config.ext.fonts,
                        timestamp: timestamp
                    }))
                    .on('glyphs', function(glyphs, options) {
                        fontObj.name = options.fontName;
                        fontObj.exts = options.formats;
                        fontObj.codePoints = glyphs;
                    })
                    .pipe(gulp.dest(config.fonts))
                    .on('end', function() {
                        gulp.src(config.fonts+'/_icon-font.tmpl')
                            .pipe(consolidate('underscore', fontObj))
                            .pipe(rename('icon-font.sass'))
                            .pipe(gulp.dest(config.fonts))
                            .on('end', function() { cb() });
                    });
            });
    });
});
```
##### _fonts.tmpl
```
<% function srcString(exts, name, path) {
    var str = "@font-face\n";
    str += "  font-family: '"+name+"'\n";

    if(_.indexOf(exts, '.eot') !== -1) {
        str += "  src: url('"+path+name+".eot')\n";
        str += "  src: url('"+path+name+".eot?#iefix') format('eot'), ";
    } else {
        str += "  src: ";
    }

    var arr = [];
    _.each(_.without(exts, '.eot'), function(ext) {
        var format = ext === '.ttf' ? 'truetype' : ext.replace('.', '');
        arr.push("url('"+path+name+ext+"') format('"+format+"')");
    });
    return str+arr.join(', ');
} %>

<% _.each(fonts, function(exts, name) { %>
<%= srcString(exts, name, path) %>
<% }) %>
```

##### _icon-font.tmpl
```
.<%= className %>:before
  font-family: '<%= name %>'
  -webkit-font-smoothing: antialiased
  -moz-osx-font-smoothing: grayscale
  font-style: normal
  font-variant: normal
  font-weight: normal
  text-decoration: none
  text-transform: none

<% _.each(codePoints, function(codePoint) { %>
.<%= className %>.<%= codePoint.name.replace('-icon', '') %>:before
  content: "\<%= codePoint.unicode[0].toUpperCase() %>"
<% }) %>
```

The `icon-font` task needs to be completed before the `fonts` task:
```javascript
var sequence    = require('run-sequence');
sequence('icon-font', 'fonts');
```

**Comment by Dobby89** [comment]
@daviestar No problem. I've picked up a few things from how you've built your tasks as well, which I'll have to look into!

**Comment by guptatarun001** [comment]
@Dobby89  I want to ask if there is any difference in the codepoints generated. Earlier my project was using font-custom to generate the fonts so the font content was in this format - "\fxxx" - where x is any random number.

Now after using GULP to automate this process the codepoints generated are like - "\Exxx" and I am not getting any icons on my page.

Please help, I am stuck here.

**Comment by Dobby89** [comment]
@guptatarun001 My codepoints get generated in the same `\EXXX` format, so that's correct. But if you're not getting the icons showing up on the page, it sounds like the problem lies elsewhere in the CSS.

* Make sure the font files are being referenced and loaded correctly in the `@font-face.` rule.
* Make sure you've set the `font-family` property on the element you're targeting to use the same font-family name as in the `@font-face` rule.

I've provided the most basic example of the resultant CSS file below.

```
@font-face {
  font-family: "iconfont";
  src: url('iconfont.eot');
  src: url('iconfont.eot?#iefix') format('eot'),
       url('iconfont.woff') format('woff'),
       url('iconfont.ttf') format('truetype'),
       url('iconfont.svg#iconfont') format('svg');
}

.icon:before {
  font-family: "iconfont"; /* same as the @font-face rule */
  content: "\E001"; /* where E001 is whatever unicode codepoints get generated by the plugin */
}
```
