### ISSUE TITLE
Unhandled rejection TypeError: tmpl is not a function

### ISSUE THREAD

**Issue by saadmhybris** [nfroidure/gulp-iconfont#162]
Hello - 

I get the following error when running the iconfont task. 
```
Unhandled rejection TypeError: tmpl is not a function
    at /node_modules/consolidate/lib/consolidate.js:780:16
    at /node_modules/consolidate/lib/consolidate.js:144:5
    at Promise._execute (/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/node_modules/bluebird/js/release/promise.js:79:10)
    at promisify (/node_modules/consolidate/lib/consolidate.js:137:10)
    at Function.exports.lodash.render (/node_modules/consolidate/lib/consolidate.js:776:10)
    at /node_modules/consolidate/lib/consolidate.js:165:27
    at /node_modules/consolidate/lib/consolidate.js:99:5
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:528:3)
```
The error seem to originate from '.pipe(consolidate('lodash', options))' if found some solutions to similar problem on other plugins, but it's not working for this one. Here is the solution for gulp-wrap plugin with the same issue - https://github.com/adamayres/gulp-wrap/commit/fdc9f9d225782c83ca26ac9b9cdcb8636337b8b0

I tried the same for gulp-iconfont, but it does not seem to work. or I am not putting it in the right place. any help would be greatly appreciated.

**Comment by yanwsh** [comment]
I have the same issue.

and i temporary solved by install loadsh to package

just run 

```
npm install --save-dev lodash
```

**Comment by NaridaL** [comment]
I'm having a hard time figuring out what's going on. As far as I can see, consolidate doesn't feature anywhere this package's dependency tree. Could you provide more details as to what exactly you were trying to do, and npm/node version, as well as the output of npm list.

@nfroidure any idea?

**Comment by saadmhybris** [comment]
installing lodash as dev dependency worked. I thought it was already included. 

everything seems to be working now, thanks, @yanwsh and thanks for looking into this @NaridaL
