### ISSUE TITLE
Generated font produces some filled icons

### ISSUE THREAD

**Issue by N-Raillot** [nfroidure/gulp-iconfont#183]
When i generate my font with
```
function buildFont() {
  return src([INPUT_SVG_GLOB])
    .pipe((gulpTransform as any)('utf8', processSvg))
    .pipe(iconfont({
      fontName: 'my-font', 
      formats: ['ttf', 'eot', 'woff', 'woff2'], 
      timestamp: runTimestamp,
      fontHeight: 1001,
      normalize: true,
      prependUnicode: true
    }))
    .pipe(dest(DIST_FONTS));
}

function processSvg(content: string, file: string): string {
  // Remove the frame <rect>.
  return content.replace(/<rect[^>]*id="Frame"[^>]*\/>/gm, '');
}
```
Some glyphs in the generated font appears filled with black, some don't : 

Expected Icon : 
<img width="118" alt="Capture d’écran 2020-10-16 à 11 45 53" src="https://user-images.githubusercontent.com/56080359/96243680-5b41ee00-0fa5-11eb-861a-3ae2a3477237.png">

Glyph in generated font :
<img width="118" alt="Capture d’écran 2020-10-16 à 11 45 38" src="https://user-images.githubusercontent.com/56080359/96243676-5aa95780-0fa5-11eb-94f2-68bee899ffc3.png">

I could not find anyone with this issue so far.

**Comment by pioug** [comment]
It happens to me sometimes as well. It can be fixed by editing the SVG by changing how the shapes are layered. Try to group some shapes and play with union, difference, intersection...
