### ISSUE TITLE
Outdated gulp-ttf2woff2 dependency causing issues on OSX Catalina.

### ISSUE THREAD

**Issue by matyasf** [nfroidure/gulp-iconfont#185]
The app uses `gulp-ttf2woff2` version 3.0.0, which uses an outdated version of `ttf2woff2` 3.0.0 which an old `node-gyp` version 4.0.0. This version is a pain to use on newer OSXes because https://github.com/nodejs/node-gyp/issues/1927 , and affects this library too.

A solution would be to update gulp-ttf2woff2 to version 4.0.0

**Comment by pioug** [comment]
I published an update https://github.com/nfroidure/gulp-iconfont/releases/tag/v11.0.0 🙏
