### ISSUE TITLE
Not working with Gulp 5

### ISSUE THREAD

**Issue by jakubzasanski** [nfroidure/gulp-iconfont#205]

**Comment by jakubzasanski** [comment]
> [Mickey]已经收到了，谢谢

is there any solution?

**Comment by pvcresin** [comment]
@jakubzasanski Your comment saved my life! Thank you so much!

**Comment by pioug** [comment]
PRs are welcome to update the example from the README! 

However, I'd like to see a repro case because `encoding` as an option for `dest()` doesn't seem to be documented https://gulpjs.com/docs/en/api/dest/. I only see it for `src()` https://gulpjs.com/docs/en/api/src/.
