### ISSUE TITLE
Font generation problem on OSX

### ISSUE THREAD

**Issue by nfroidure** [nfroidure/gulp-iconfont#32]
It seems that a few people are facing some bugs but it also seems to be pretty hard to reproduce. In order to find a similirity between the configurations of each users having this problem, please, could you tell:
- what is your OS
- which kind of hard drive you have (HD, SSD),
- run npm -v && node -v
- your gulp global and local version
- any other information that could help according to you.

**Comment by danhere** [comment]
I'm also having this issue, though I'm not sure its OSX only. I've been following gulp-ruby-sass and their newest version mentions new file globbing. I ended up removing my `/icons/*.svg` source and putting a single file. Everything works. Maybe the way the files are passed in needs to be reworked somehow?

**Comment by lmartins** [comment]
Weirdly on my setup it started to work without issues a few weeks ago. I have no clue of what changed.

**Comment by nfroidure** [comment]
Closing since the issue looks solved. Probably unrelated to this plugin, fell free to reopen if you encounter this problem again.
