### ISSUE TITLE
Additional space in IE

### ISSUE THREAD

**Issue by nickdunn** [nfroidure/gulp-iconfont#38]
I know this has come up before and has been fixed, but am still seeing this bug.

When viewing the generated font in IE/Windows there's additional spacing under the character. This does not appear in Chrome/Windows (or any OSX browser). After having dug into this a while back I recall it may be to do with either floating points or Windows/OSX using different tables for ascender/descender heights. My initial thought was that it was the tables bug, but then I would have expected to also see this bug in Chrome/Windows.

I've put together a small repo to demonstrate the bug.

https://github.com/nickdunn/gulp-iconfont-testcase

Chrome/Windows (good)
![#](https://raw.githubusercontent.com/nickdunn/gulp-iconfont-testcase/master/sreenshots/chrome-windows.png)

IE9/Windows (bug)
![#](https://raw.githubusercontent.com/nickdunn/gulp-iconfont-testcase/master/sreenshots/ie9-windows.png)

**Comment by nfroidure** [comment]
https://github.com/fontello/svg2ttf/issues/37

Closing since the problem sits elsewhere.

**Comment by puzrin** [comment]
Is it still a problem with last svg2ttf?

**Comment by nickdunn** [comment]
Same result using gulp-iconfont v5.0.0. This looks to be using gulp-svg2ttf v1.1.4 and therefore svg2ttf v2.1.0.

![screen shot 2015-11-12 at 18 22 25](https://cloud.githubusercontent.com/assets/39560/11127101/59653c70-896a-11e5-920e-a46df1226a96.png)

**Comment by puzrin** [comment]
@nickdunn do you have info, which combinations of IE / Win are affected by this problem? This info could be helpful (save some time to setup VM images)

**Comment by nickdunn** [comment]
I'm using the IE9 VM from https://github.com/xdissent/ievms:

1. Install Virtualbox
2. `curl -s https://raw.githubusercontent.com/xdissent/ievms/master/ievms.sh | env IEVMS_VERSIONS="9" bash`

**Comment by puzrin** [comment]
That's a bit strange. If this bug existed in all IE, it could be reported in fontello. May be, problem in SVG, generated for svg2ttf input?

Could you do another test? Import files to fontello, as custom icons, generate font and check if demo from generated archive behave bad.
