### ISSUE TITLE
Formats

### ISSUE THREAD

**Issue by fmal** [nfroidure/gulp-iconfont#39]
1. Is it possible to add WOFF2 support ?
2. SVG in `@fontface` is deprecated in some of the newer browsers, so it'd be nice to have an option for dropping this format. There's no need for it anymore.

Thanks!

**Comment by nfroidure** [comment]
1. yes
2. yes

Feel free to PR the project.

I'll have a look at it in a few weeks otherwise.

**Comment by nfroidure** [comment]
It looks like the WOFF2 support cannot be done without external utility https://github.com/sapegin/grunt-webfont/wiki/WOFF2-support . I think it would be better to have a full node ttf2woff2 or woff2woff2 converter but couldn't find it already.

More infos: https://gist.github.com/sergejmueller/cf6b4f2133bcb3e2f64a

So for woff2 font support, using gulp-spawn should do the job. https://www.npmjs.com/package/gulp-spawn .

**Comment by nfroidure** [comment]
1- is resolved https://github.com/nfroidure/gulp-iconfont/issues/47
2- coming soon ;)

**Comment by nfroidure** [comment]
2 is done. Use `options.svg = false`

**Comment by teohhanhui** [comment]
I hope you'd have added a "formats" option instead. Let the user decide which formats are needed... (I don't want/need EOT)

**Comment by teohhanhui** [comment]
In any case, there's a mismatch between the documentation and code:

> #### options.svg
> Type: `Boolean`
> Default value: `false`
>
> Since SVG fonts are deprecated in some browsers, they are disabled per default.
> You may want to continue generating them.

vs.

```js
  options.svg = 'boolean' === typeof options.svg ? options.svg : true;
```

**Comment by nfroidure** [comment]
Nice catch, i'll patch it asap.

**Comment by nfroidure** [comment]
About the formats option, i'll accept a PR with tests doing so for the next major version.
