### ISSUE TITLE
Path Direction Matters

### ISSUE THREAD

**Issue by Pinpickle** [nfroidure/gulp-iconfont#41]
Even if the `fillrule` for an svg is set to `evenodd`, some platforms will treat it as `nonzero`. This means that for a path to be cut out of another path, they have to have alternating path direction. I ran into this issue when trying to make an icon font with Sketch. I was having logos inside circles appear as just circles on Android.

I think this just needs to be added to the docs, because there is not much to be done.

For a little more info, see: fontello/svg2ttf#35

**Comment by nfroidure** [comment]
Would you add a section to explain this in the README file where icons flavored format is specified?

**Comment by nfroidure** [comment]
Closing since no news.
