### ISSUE TITLE
Font is blurry

### ISSUE THREAD

**Issue by DusanMilko** [nfroidure/gulp-iconfont#43]
My icon font comes out blurry, and the icons are all square in ratio, is there a way to retain ratios per icon?
The icon also doesnt seem to be vertically aligned even after setting variable:

The 2 images below are 2 fonts built using same svgs, one using gulp-iconfont and one provided by zurb foundation

Chrome: (Font created using gulp-iconfont and zurb foundation svg files)
![screen shot 2015-04-09 at 2 15 08 pm](https://cloud.githubusercontent.com/assets/302239/7074036/a2cef248-dec5-11e4-8c87-9f2cb7a25043.png)

Expected:  (Font provided by zurb foundation using same svg files)
![screen shot 2015-04-09 at 2 15 03 pm](https://cloud.githubusercontent.com/assets/302239/7074048/b1384686-dec5-11e4-8d17-ce01b39c572b.png)

**Comment by nfroidure** [comment]
The difference could come from ttfautohint usage.  https://github.com/nfroidure/gulp-iconfont#font-hinting

Did you tried to use it?

**Comment by nfroidure** [comment]
Also fontHeight option may help bu setting to 1000 or greater. Closing anyway since no news...
