### ISSUE TITLE
very strange unicode characters with v2.0.0

### ISSUE THREAD

**Issue by bm2u** [nfroidure/gulp-iconfont#50]
Came from 1.0.2 update to 2.0.0. After replacing old `codepoints` with new `unicode` (options, hooks, etc.), I got very strange unicode-characters as a result from my custom scss template. I'd appreciate any suggesstions. :+1: 

`$<%= className %>-map : (
<%= glyphs.map(function(glyph){
  return glyph.name + ': "' + '\\' + glyph.unicode.toString(16).toUpperCase() + '"'
}).join(',\n  ') %>
);`

Result scss-file:
![bm2u-001874](https://cloud.githubusercontent.com/assets/11159476/8084537/c7c8f5c0-0f8b-11e5-8528-850cc2454c8b.png)

Result html (chrome):
![bm2u-001875](https://cloud.githubusercontent.com/assets/11159476/8084442/525709da-0f8b-11e5-9dca-6005d45258a9.png)

**Comment by nfroidure** [comment]
You can simply return the unicode string:
`$<%= className %>-map : (
<%= glyphs.map(function(glyph){
  return glyph.name + ': "' + glyph.unicode + '"'
}).join(',\n  ') %>
);`

**Comment by bm2u** [comment]
thx for your quick reply. done this already, but unfortunately with same (strange) results

**Comment by nfroidure** [comment]
Probably en encoding problem, try: '\\' + glyph.unicode.charCodeAt(0).toString(16) + ';'

**Comment by bm2u** [comment]
nope! got the same problem. I supposed lodash so I pushed it from 3.8.0 to 3.9.3 without success. Any ideas?!

**Comment by nfroidure** [comment]
Won't be able to help anymore since it looks unrelated to gulp-iconfont itself but with your particular setup.

Do you use another plugin in conjunction with gulp-iconfont ? If so, it is probably not yet updated to support it so fill an issue in it.

**Comment by nfroidure** [comment]
To support its 2.0.0 version ;)

**Comment by lcdsantos** [comment]
Try this:
```
$<%= className %>-map : ( <%= glyphs.map(function(glyph){ return glyph.name + ': "' + '\\' + glyph.unicode[0].charCodeAt(0).toString(16).toUpperCase() + '"' }).join(',\n ') %> );
```

**Comment by bm2u** [comment]
@lcdsantos thx - that did the magic :+1:
