### ISSUE TITLE
Cannot find module 'gulp-ttf2woff2'

### ISSUE THREAD

**Issue by whalesingswee** [nfroidure/gulp-iconfont#55]
When I run npm install with this module, I ran into this issue:
![screenshot_2015-06-22_17_41_17](https://cloud.githubusercontent.com/assets/1246007/8279336/3adad38e-1906-11e5-8c94-02b95c99f615.jpg)

Which can be solve by installing 'gulp-ttf2woff2' this dependency alone.

**Comment by nfroidure** [comment]
Wieird that the travis build worked. Feel free to reopen if the problem persists.
