### ISSUE TITLE
Support for non-BMP unicode characters (5 and 6 digit unicode)

### ISSUE THREAD

**Issue by alsoscotland** [nfroidure/gulp-iconfont#57]
I see a brief mention of this in https://github.com/nfroidure/gulp-iconfont/issues/25 but have had little luck with implementation when using unicode chars with 5 and 6 digit representations.

As an example I am trying to use the unicode character u1F178 (Negative Squared Latin Capital Letter I) as a unicode fallback for an icon representing a button to toggle italic text.

My current svg file is named: U1F178-text-italic.svg.

If it is not possible to use unicode chars that extend beyond the uFFFF range, would it be possible to allow for the usage of surrogate pairs?

something along these lines:
UD83C-UDD78-text-italic.svg

**Comment by nfroidure** [comment]
@alsoscotland there is something in the pipe for this, see @teohhanhui work https://github.com/nfroidure/svgicons2svgfont/pull/37

It is just a matter of time since it need to be published via svgicons2svgfont then gulp-svgicons2svgfont and finally gulp-iconfont :). Feel free to help !

**Comment by teohhanhui** [comment]
@alsoscotland In the meantime you can try this:

```sh
cd /path/to/project/node_modules/gulp-iconfont/node_modules/gulp-svgicons2svgfont
sed -i .bak 's/"svgicons2svgfont": "3\.0\.2"/"svgicons2svgfont": "nfroidure/svgicons2svgfont#1764298"/' package.json
npm install --production
cd /path/to/project
npm shrinkwrap
```

**Comment by alsoscotland** [comment]
@nfroidure & @teohhanhui That is fantastic.  Thanks so much.

**Comment by nfroidure** [comment]
Fixed.

**Comment by alsoscotland** [comment]
@nfroidure are you going to bump to "gulp-svgicons2svgfont": "2.2.1"  and pick up the change?

**Comment by nfroidure** [comment]
I'm stucked since it would break the build :( https://github.com/nfroidure/gulp-iconfont/issues/65
