### ISSUE TITLE
the icon is not appearing if only one icon was added

### ISSUE THREAD

**Issue by whalesingswee** [nfroidure/gulp-iconfont#59]
> this only happens to chrome

Have you guys tested with placing only one svg on the image folder?
It's kinda weird the icon won't appear when there's only one, but adding another svg made it worked.

What made it even weird is on the situation when there's only one icon, safari and firefox are working just fine, but chrome is not. While adding another second image fixed the issue on the chrome.

![screenshot 2015-06-24 15 35 23](https://cloud.githubusercontent.com/assets/1246007/8324828/b09e871a-1a86-11e5-86fb-4e2c007836e8.png)
![screenshot 2015-06-24 15 35 11](https://cloud.githubusercontent.com/assets/1246007/8324829/b09fd944-1a86-11e5-908e-e75bab680388.png)

**Comment by nfroidure** [comment]
Probably related to the format of the font used inChrome. Try to find which format is used by Chrome, remove it from your CSS to see if it still has that behavior. If not, submit the issue to the repo related to the format, if yes, it is probably a Chrome issue.

**Comment by whalesingswee** [comment]
I believe it's more likely a chrome issue because it's kinda hard to believe we've several output font type (ttf, eot, woff, svg) to use and none of it Chrome supports? Not to mention it's only not working when there's only 1 svg for it to render, it works when there's 2 or more image files.
