### ISSUE TITLE
Set custom metadata for name

### ISSUE THREAD

**Issue by mattdrose** [nfroidure/gulp-iconfont#62]
I was wondering if there was a way to set custom metadata, specifically for `name`. I use multiple repos of icon fonts for my projects, so I sometimes have two svg's from separate repos with the same name. It would be nice if I could somehow set a custom name in these situations.

Something like:
```
[
  {
    "src": "./icomoon/book.svg",
    "name": "book"
  },
  {
    "src": "./iconic/book.svg",
    "name": "book-2"
  }
]
```

**Comment by sabberworm** [comment]
I think this can be solved in concert with the https://github.com/nfroidure/svgicons2svgfont/issues/38.

**Comment by mattdrose** [comment]
Nice. Even if you could set a custom function to map through the metadata, then the user could configure according to their own needs :)

**Comment by nfroidure** [comment]
@mattdrose feel free to give your advice on the right implementation since we're not fully sure on the best way to achieve this.

**Comment by mattdrose** [comment]
Maybe you could have an option for [nfroidure/svgicons2svgfont](https://github.com/nfroidure/svgicons2svgfont) to set a metadata function that gets mapped to the metadata. Then I could solve my problem with this:

```javascript
var names = {
  './iconic/book.svg': 'book-2'
};
```
```javascript
options: {
  "metadata": function(glyph) {
    if (!!names[glyph.path]) glyph.name = names[glyph.path];
    return glyph;
  }
}
```

You could also solve my particular use case by appending ``-x`` to glyph names, where ``x`` is the iteration of duplicate names.

**Comment by nfroidure** [comment]
Done, will ship once https://github.com/nfroidure/gulp-svg2ttf/issues/5 will be resolved.

**Comment by mattdrose** [comment]
Awesome. Thanks for your help with this!
