### ISSUE TITLE
Update npm version

### ISSUE THREAD

**Issue by suisho** [nfroidure/gulp-iconfont#65]
Could you update version?
I want tp use timestamp option ( #58 ) :smiley:

**Comment by nfroidure** [comment]
I'm waiting for this to be published https://github.com/fontello/svg2ttf/pull/38 otherwise it will break the tests.

**Comment by suisho** [comment]
Ok, thank you.

**Comment by futekov** [comment]
The pending issue (https://github.com/fontello/svg2ttf/pull/38) has been merged and published (https://github.com/fontello/svg2ttf/commit/952ed3d451844a160ace0a6c88f972cc5b9db972).

**Comment by nfroidure** [comment]
I plan to. I have a few things to fix before:
- https://github.com/nfroidure/gulp-iconfont/issues/67
- https://github.com/nfroidure/gulp-iconfont/issues/64
- https://github.com/nfroidure/svgicons2svgfont/issues/40

Fell free to help

**Comment by greypants** [comment]
:+1:

**Comment by nfroidure** [comment]
I just solved https://github.com/nfroidure/svgicons2svgfont/issues/40 since this is the more critical issue, i'll make an update today and add a disclaimer for the 2 other bugs in the README temporarily.

**Comment by nfroidure** [comment]
Published.

**Comment by suisho** [comment]
Thank you! :+1:
