### ISSUE TITLE
md5 is different every time when generate fonts form the same svg icon.

### ISSUE THREAD

**Issue by calledT** [nfroidure/gulp-iconfont#70]
![capture](http://ww3.sinaimg.cn/large/68250c36gw1euamh6kg5dj20hd05tgno.jpg)

as show in picture, only svg's md5 would consistent each time.

I use gulp-rev to append hash

**appendUnicode** is true

**Comment by nfroidure** [comment]
https://github.com/nfroidure/gulp-iconfont/issues/65

**Comment by greypants** [comment]
@calledT Here's exactly what's happening: https://github.com/fontello/svg2ttf/issues/33

We added the `ts` (timestamp) option in svg2ttf to address it. As soon as all the dependencies are up to date, and the `timestamp` option gets passed, everything will work.

If this is critical, I have [a super convoluted workaround](https://github.com/greypants/gulp-starter/blob/2.0/gulpfile.js/tasks/rev/rev-iconfont-workaround.js) that works... but I'm looking forward to being able to trash that as soon as `timestamp` works.

@nfroidure thanks for your work on this!

**Comment by calledT** [comment]
@greypants @nfroidure thx~, wait this plugin update to npm

**Comment by greypants** [comment]
![happy dance!](http://media3.giphy.com/media/bTzFnjHPuVvva/giphy.gif)
