### ISSUE TITLE
Dépendance ttf2woff2-1.2.2.tgz manquante ?

### ISSUE THREAD

**Issue by Scriptura** [nfroidure/gulp-iconfont#78]
Bonjour Nicolas,

J'ai tenté d'installer votre plugin prometteur, mais j'ai une erreur à l'installation. J'ai donc tapé ceci :

    $ sudo npm install gulp-iconfont --save-dev

 Et le terminal me retourne ceci :

    npm ERR! fetch failed https://registry.npmjs.org/ttf2woff2/-/ttf2woff2-1.2.2.tgz
    npm ERR! fetch failed https://registry.npmjs.org/ttf2woff2/-/ttf2woff2-1.2.2.tgz
    npm ERR! fetch failed https://registry.npmjs.org/ttf2woff2/-/ttf2woff2-1.2.2.tgz
    npm ERR! network socket hang up
    npm ERR! network This is most likely not a problem with npm itself
    npm ERR! network and is related to network connectivity.
    npm ERR! network In most cases you are behind a proxy or have bad network settings.
    npm ERR! network 
    npm ERR! network If you are behind a proxy, please make sure that the
    npm ERR! network 'proxy' config is set properly.  See: 'npm help config'    

    npm ERR! System Darwin 14.1.0
    npm ERR! command "node" "/usr/local/bin/npm" "install" "gulp-iconfont" "--save-dev"
    npm ERR! cwd /Users/moi/Documents/Archives/etc
    npm ERR! node -v v0.10.35
    npm ERR! npm -v 1.4.28
    npm ERR! code ECONNRESET
    npm ERR! not ok code 0

Il semble qu'il manque une dépendance .tgz, mais n'étant pas familier de ce genre de process j'ai peut-être manqué quelque chose...

**Comment by nfroidure** [comment]
`npm ERR! network socket hang up`

Il y a eu un problème réseau, il suffit de recommencer avec une connexion stable.
https://www.npmjs.com/package/ttf2woff2

**Comment by Scriptura** [comment]
Ok, j'ai déjà essayé plusieurs fois mais ce n'est peut-être pas mon jour. Je tenterais plus tard...
Merci pour la réponse !
