### ISSUE TITLE
spawn is not defined

### ISSUE THREAD

**Issue by bmathews** [nfroidure/gulp-iconfont#81]
https://github.com/nfroidure/gulp-iconfont/blob/master/src/index.js#L43

throws an exception when autohint is true

**Comment by nfroidure** [comment]
This bad commit is responsible https://github.com/nfroidure/gulp-iconfont/commit/dd10a5a4d26d9b24677759f47a46cadb98fb6545#diff-1fdf421c05c1140f6d71444ea2b27638L11

Reverting...
