### ISSUE TITLE
support node 0.12.7

### ISSUE THREAD

**Issue by evilebottnawi** [nfroidure/gulp-iconfont#85]
Many projects and repos are on node 0.12.7, not only node 4

**Comment by nfroidure** [comment]
@evilebottnawi the 4.* branch will be maintained for that matter. Until ttf2woff2 goes to use nan.

**Comment by nfroidure** [comment]
Now using nan, should work on old node versions. Will try to update the engines support if the travis builds are fine.

**Comment by nfroidure** [comment]
A version bump will be done but in the meanwhile, reinstalling will solve the issue.

**Comment by evilebottnawi** [comment]
@nfroidure thanks
