### ISSUE TITLE
font change so every build

### ISSUE THREAD

**Issue by ebess** [nfroidure/gulp-iconfont#95]
Hey guys,
I'm really familiar with the build on font and trying just to use this plugin which works out so far. One think bothers me: on every build of the iconfont the resulting font changes so it's in my local changes all the time. Why the font changes despite I'm not changing the svg icons? How can I solve this issue?
TY

**Comment by nfroidure** [comment]
See the gulp-svg2ttf timestamp option https://github.com/nfroidure/gulp-iconfont#iconfontoptions

**Comment by jreading** [comment]
I have the same issue. Not sure what to set that option to to avoid this.

**Comment by nfroidure** [comment]
TTF font have a special field in which the "Creation date" is set. It probably don't hurt to set it to 0 but i thunk the best would be to set it to the Gulp startup time. That way it won't change in the same coding session but would till be a valid information.

**Comment by ebess** [comment]
thats pretty bad @nfroidure.
in case you have continuous delivery on every deploy you will force the client to redownload the icon font despite nothing changed but the timestamp. setting it to a constant worked out for me.

**Comment by nfroidure** [comment]
For continous deployment i assume that the best would be to take the recenter file last modified date. It can be easy done with a gulp plugin emitting an event providing the timestamp when it ends.

**Comment by ebess** [comment]
if you deploy 10 times a day its 10 times font download resulting in slower page and more traffic without any benefit. but its up to everyone now to use it ;)

**Comment by nfroidure** [comment]
Did you read my previous message?

**Comment by jreading** [comment]
Wouldn't a checksum be better anyway? What's the point of the timestamp?


Sent from my T-Mobile 4G LTE Device

-------- Original message --------

**Comment by sabberworm** [comment]
I have solved this problem as follows: first I generate a checksum and store it in the `package.json` with the current timestamp. This way the timestamp changes only when the checksum changes.

The relevant parts of my gulpfile:

```javascript
'use strict';

var fs = require('fs');
var path = require('path');
var crypto = require('crypto');

var gulp = require('gulp');
var iconfont = require('gulp-iconfont');
var intercept = require('gulp-intercept');
var naturalSort = require('gulp-natural-sort');

var del = require('del');

var PACKAGE = require('./package.json');
if(!('timestamps' in PACKAGE)) {
	PACKAGE.timestamps = {};
}

var FILES = '/your/path/here/*.svg';
var FONT_NAME = 'your-name';
var DESTINATION = 'your-name';

var digest;

gulp.task('digest', function() {
	var hash = crypto.createHash('sha1');
	return gulp.src([FILES])
		.pipe(naturalSort())
		.pipe(intercept(function(file){
			hash.update(file.relative);
			hash.update(file.contents);
		}))
		.on('end', function() {
			digest = hash.digest('base64').replace(/[+\/=]+/g, '').substring(0, 5);
			if(!(digest in PACKAGE.timestamps)) {
				PACKAGE.timestamps[digest] = Math.round(Date.now()/1000);
			}
			fs.writeFileSync('./package.json', JSON.stringify(PACKAGE, null, 2));
		});
});

gulp.task('clean', ['digest'], function() {
	var glob = path.join(DESTINATION, FONT_NAME);
	return del([glob+'*', '!'+glob+'@'+digest+'*'], {force: true});
});

gulp.task('generate', ['digest'], function() {
	var options = {
		fontName: FONT_NAME,
		fileName: FONT_NAME+'@'+digest,
		timestamp: PACKAGE.timestamps[digest]
	};
	return gulp.src([FILES])
		.pipe(iconfont(options))
		.pipe(gulp.dest(DESTINATION));
});
```

This also adds the checksum to the filename which allows the server to send an `Expires` header with a value of one year into the future, so the browser won’t try to re-download the same version of the font again. If you don’t want this, just delete the `fileName` option and remove the `clean` task.

Note that if you have the `appendUnicode` option set, you need to generate your font twice after adding a new SVG because the digest will have changed. Also you may want to save your checksums somewhere other than the package.json file. For me it just seemed very convenient.
