### ISSUE TITLE
Unable to convert the attached icon 

### ISSUE THREAD

**Issue by ivks** [nfroidure/gulp-iconfont#96]
Both original and edited as per best practices mentioned here
https://github.com/nfroidure/gulp-iconfont/issues/16
[Archive.zip](https://github.com/nfroidure/gulp-iconfont/files/67069/Archive.zip)

The output svg font file mentions: 
<glyph glyph-name="u994-flipcamera6"
      unicode="&#xE02F;"
      horiz-adv-x="1024" d="" />

Note: I have other svgs which works perfectly fine, but there are some cases where i do not find them working. Would like to understand the reason behind it.

**Comment by nfroidure** [comment]
Your image actually contains no vectorial shapes but an embedded bitmap image.
