### ISSUE TITLE
.woff in chrome can't show

### ISSUE THREAD

**Issue by y-ry** [nfroidure/gulp-iconfont#97]
hi,thank you for nice plugin.

I tried to create my web font with gulp-iconfont & gulp-iconfont-css.

Safari and firefox will be show no problem.
But Chrome(47.0.2526.106 (64-bit)) on mac ,icon doesn't display.

== my package.json==
  "devDependencies": {
    "browser-sync": "^2.10.1",
    "del": "^2.2.0",
    "gulp": "^3.9.0",
    "gulp-autoprefixer": "^3.1.0",
    "gulp-clean": "^0.3.1",
    "gulp-concat": "^2.6.0",
    "gulp-csscomb": "^3.0.6",
    "gulp-cssnext": "^1.0.1",
    "gulp-iconfont": "^5.0.1",
    "gulp-iconfont-css": "^2.0.0",
    "gulp-plumber": "^1.0.1",
    "gulp-rename": "^1.2.2",
    "gulp-sass": "^2.1.0",
    "gulp-sourcemaps": "^1.6.0",
    "gulp-styledocco": "0.0.3",
    "gulp-watch": "^4.3.5",
    "gulp-webpack": "^1.5.0",
    "run-sequence": "^1.1.5",
    "underscore": "^1.8.3"
  },

==my font task==
gulp.task('iconfont',function(){
    gulp.src(dir.src.font+'/*.svg')
    .pipe(plumber())
    .pipe(iconfontCss({
        fontName: 'mrmIconFont',
        path: './'+dir.src.fontTemplate+'/_icons.scss',
        targetPath: '../../../'+dir.src.scss+'/fonts/_icon.scss',
        fontPath: dir.dst.cssFontPath+'/'
    }))
    .pipe(iconfont({
        fontName: 'myIconFont',
        formats: ['ttf', 'eot', 'woff','svg'],
    }))
    .pipe(gulp.dest(dir.dst.font))
    .on('error', function(err) {
        console.log(err.message);
    });
});

**Comment by nfroidure** [comment]
Sorry but it looks like a CSS issue or something, please submit it to StackOverflow.
