### ISSUE TITLE
Gulp4 - no 'glyphs' event

### ISSUE THREAD

**Issue by daviestar** [nfroidure/gulp-iconfont#98]
Hey

Just a heads up - 

I was quickly messing with Gulp4 to see if `gulp.series` could fix some async issues I've been having.  I was able to get the rest of my gulpfile working, but couldn't get the gulp-iconfont task running due to the `glyphs` event not firing.

Cheers.

**Comment by nfroidure** [comment]
Hard to tell without an example of the failing code but it looks like custom stream events aren't echoed by `gulp.series`. Worth noting i didn't give a try to Gulp 4 yet, feel free to PR the project or at least create a failing test case in order to reproduce the problem.

**Comment by nfroidure** [comment]
Closing since no news.
